# Generated by Django 5.2.12 on 2026-03-16 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("drivers", "0006_driver_available_time_driver_current_lat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_lat", models.FloatField()),
                ("pickup_lng", models.FloatField()),
                ("drop_lat", models.FloatField()),
                ("drop_lng", models.FloatField()),
                (
                    "pickup_city",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("drop_city", models.CharField(blank=True, default="", max_length=128)),
                ("booking_time", models.DateTimeField(auto_now_add=True)),
                ("truck_type", models.CharField(max_length=64)),
                ("distance_km", models.FloatField(default=0.0)),
                (
                    "estimated_fare",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "final_fare",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "booking_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("driver_assigned", "Driver assigned"),
                            ("in_transit", "In transit"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="drivers.driver",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="customers.customer",
                    ),
                ),
            ],
        ),
    ]
