# Generated by Django 5.2.12 on 2026-03-16 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
        ("drivers", "0006_driver_available_time_driver_current_lat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclinedBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declined_by_drivers",
                        to="bookings.booking",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declined_bookings",
                        to="drivers.driver",
                    ),
                ),
            ],
            options={
                "unique_together": {("booking", "driver")},
            },
        ),
    ]
