# Generated by Django 4.2.29 on 2026-03-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_declined_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="load_type",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.DeleteModel(
            name="DeclinedBooking",
        ),
    ]
