# Generated by Django 4.2.29 on 2026-03-18 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0012_driver_fcm_token_driver_fcm_token_updated_at"),
        ("bookings", "0005_booking_advance_amount_booking_payment_due_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="last_batch_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="search_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="search_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BookingDriverRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="sent",
                        max_length=16,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_requests",
                        to="bookings.booking",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_requests",
                        to="drivers.driver",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["booking", "status"],
                        name="bookings_bo_booking_eba66b_idx",
                    ),
                    models.Index(
                        fields=["driver", "status"],
                        name="bookings_bo_driver__9c8f31_idx",
                    ),
                ],
                "unique_together": {("booking", "driver")},
            },
        ),
    ]
