# Generated by Django 5.2.12 on 2026-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
