# Generated by Django 5.2.12 on 2026-03-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0002_driver_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="vehicle_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="driver",
            name="vehicle_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
