# Generated by Django 5.2.12 on 2026-03-16 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0004_vehicletype"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("is_online", models.BooleanField(default=False)),
                (
                    "current_city",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "current_area",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "destination",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="drivers.driver",
                    ),
                ),
            ],
        ),
    ]
