# Generated by Django 5.2.12 on 2026-03-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0005_driverlocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="available_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="current_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="current_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="destination_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="destination_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="driver",
            name="last_location_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="rating",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="truck_capacity",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="driver",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, unique=True
            ),
        ),
    ]
