# Generated by Django 4.2.29 on 2026-03-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0006_driver_available_time_driver_current_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverlocation",
            name="bid_amount",
            field=models.FloatField(
                blank=True,
                help_text="Driver's minimum bid for this route (₹)",
                null=True,
            ),
        ),
    ]
