# Generated by Django 4.2.29 on 2026-03-17 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0007_add_bid_amount_to_driver_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_text",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "destination_text",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("destination_lat", models.FloatField(blank=True, null=True)),
                ("destination_lng", models.FloatField(blank=True, null=True)),
                ("available_from", models.DateTimeField(blank=True, null=True)),
                (
                    "bid_amount",
                    models.FloatField(
                        blank=True,
                        help_text="Driver's minimum bid for this route (₹)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="drivers.driver",
                    ),
                ),
            ],
        ),
    ]
