# Generated by Django 4.2.29 on 2026-03-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0008_add_driver_routes"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicletype",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="vehicle_icons/"),
        ),
    ]
