# Generated by Django 4.2.29 on 2026-03-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0009_add_vehicle_type_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="insurance_image",
            field=models.ImageField(blank=True, null=True, upload_to="driver_docs/"),
        ),
        migrations.AddField(
            model_name="driver",
            name="license_image",
            field=models.ImageField(blank=True, null=True, upload_to="driver_docs/"),
        ),
        migrations.AddField(
            model_name="driver",
            name="permit_image",
            field=models.ImageField(blank=True, null=True, upload_to="driver_docs/"),
        ),
        migrations.AddField(
            model_name="driver",
            name="rc_book_image",
            field=models.ImageField(blank=True, null=True, upload_to="driver_docs/"),
        ),
    ]
