# Generated by Django 4.2.29 on 2026-03-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0010_driver_insurance_image_driver_license_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="route_locked",
            field=models.BooleanField(default=False),
        ),
    ]
