# Generated by Django 5.2.12 on 2026-03-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_distance_limit_km",
                    models.FloatField(
                        default=50.0,
                        help_text="Max distance (km) for short-distance city transport pricing.",
                    ),
                ),
                (
                    "long_distance_limit_km",
                    models.FloatField(
                        default=500.0,
                        help_text="Threshold beyond which long-distance pricing applies (informational).",
                    ),
                ),
                (
                    "pickup_radius_km",
                    models.FloatField(
                        default=30.0,
                        help_text="Max distance (km) from driver current location to user pickup.",
                    ),
                ),
                (
                    "destination_radius_km",
                    models.FloatField(
                        default=25.0,
                        help_text="Max distance (km) from driver destination to user drop.",
                    ),
                ),
                (
                    "base_fare_short_distance",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        help_text="Base fare for short distance (e.g. ₹100).",
                        max_digits=10,
                    ),
                ),
                (
                    "per_km_rate_short_distance",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        help_text="Per km rate for short distance.",
                        max_digits=8,
                    ),
                ),
                (
                    "per_km_rate_long_distance",
                    models.DecimalField(
                        decimal_places=2,
                        default=25.0,
                        help_text="Per km rate for long distance (no base fare).",
                        max_digits=8,
                    ),
                ),
                (
                    "platform_commission_percentage",
                    models.FloatField(
                        default=10.0, help_text="Platform commission % (e.g. 10 = 10%)."
                    ),
                ),
                (
                    "surge_multiplier",
                    models.FloatField(
                        default=1.0, help_text="Surge multiplier (1.0 = no surge)."
                    ),
                ),
                (
                    "driver_location_update_interval",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Expected driver location update interval in seconds (e.g. 10–15).",
                    ),
                ),
                (
                    "enable_driver_bidding",
                    models.BooleanField(
                        default=False, help_text="Allow drivers to bid on bookings."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admin settings",
                "verbose_name_plural": "Admin settings",
            },
        ),
    ]
