# Generated by Django 5.2.12 on 2026-03-16 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("drivers", "0006_driver_available_time_driver_current_lat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleTypeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_distance_limit_km", models.FloatField(default=50.0)),
                ("long_distance_limit_km", models.FloatField(default=500.0)),
                ("pickup_radius_km", models.FloatField(default=30.0)),
                ("destination_radius_km", models.FloatField(default=25.0)),
                (
                    "base_fare_short_distance",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
                ),
                (
                    "per_km_rate_short_distance",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=8),
                ),
                (
                    "per_km_rate_long_distance",
                    models.DecimalField(decimal_places=2, default=25.0, max_digits=8),
                ),
                ("platform_commission_percentage", models.FloatField(default=10.0)),
                ("surge_multiplier", models.FloatField(default=1.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle_type",
                    models.OneToOneField(
                        help_text="e.g. Pickup, 12 Wheeler, Container",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_settings",
                        to="drivers.vehicletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle type settings",
                "verbose_name_plural": "Settings by vehicle type",
            },
        ),
    ]
