# Generated by Django 5.2.12 on 2026-03-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_vehicle_type_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("message", models.TextField()),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("all", "All users"),
                            ("drivers", "All drivers"),
                            ("customers", "All customers"),
                            ("user", "Individual user"),
                        ],
                        default="all",
                        max_length=16,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        blank=True,
                        choices=[("driver", "Driver"), ("customer", "Customer")],
                        default="",
                        max_length=16,
                    ),
                ),
                ("user_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "notification_type",
                    models.CharField(
                        blank=True, default="general_notification", max_length=32
                    ),
                ),
                ("send_result", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Push notification",
                "verbose_name_plural": "Push notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
