# Generated by Django 5.2.12 on 2026-03-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="fcm_token",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="fcm_token_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
